### ISSUE TITLE
Issue with ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by jagmeetsidhu** [chrivand/talos_blog_to_casebook#2]
Hi there,

Thanks so much for developing this tool. It will be very useful for our needs.

I tried setting everything up but I seem to be encountering the following error when I start the script:
<img width="508" alt="scripterror" src="https://user-images.githubusercontent.com/47167588/52025296-c849f180-253e-11e9-9801-0adf6c2f0b1f.png">

I have set up the requirements, and config.json file with my client ID and secret. I have not modified the script.
<img width="582" alt="config" src="https://user-images.githubusercontent.com/47167588/52025351-f0d1eb80-253e-11e9-905c-7f7f53351a61.png">
<img width="629" alt="folderlist" src="https://user-images.githubusercontent.com/47167588/52025357-f62f3600-253e-11e9-9971-3fbdc152c174.png">

I am running Python 3.6.5 on Mac OS Mojave 10.14.3

Any idea what could be the issue?

Thanks again!

Regards,
Jag

**Comment by chrivand** [comment]
Handled this through email. I will post the newer version soon. The config library was missing from the requirments.txt file, however I was not even using the library.

**Comment by chrivand** [comment]
fixed in v2.0
